server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Enable byte-range requests for video scrubbing and caching
    location ~* \.(mp4|webm|gif|webp|jpg|jpeg|png)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
